name: 'Composer update'
description: 'Runs a composer update such that you can create a PR if there are any updates'
inputs:
  working-dir:
    description: 'Directory of the composer.lock'
    required: true
    default: './'
  composer-token:
    description: 'API token for composer'
    required: true
  composer-cache:
    description: 'Path to composer cache'
    required: true
    default: /tmp/composer-cache
  ignore-platform-reqs:
    description: 'What platform requirements should be ignored'
    required: true
    default: --ignore-platform-req=ext-gprc
outputs:
  diff:
    description: "Markdown table with the changed versions"
    value: ${{ steps.get-diff.outputs.diff }}
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: composer install --no-progress --no-scripts ${{ inputs.ignore-platform-reqs }} --no-autoloader -d ${{ inputs.working-dir }}
      env:
        COMPOSER_CACHE_DIR: ${{ inputs.composer-cache }}
        COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ inputs.composer-token }}"}}'

    - name: Update dependencies
      shell: bash
      run: composer update --no-progress --no-scripts ${{ inputs.ignore-platform-reqs }} --no-autoloader -d ${{ inputs.working-dir }}
      env:
        COMPOSER_CACHE_DIR: ${{ inputs.composer-cache }}
        COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ inputs.composer-token }}"}}'

    - name: Create diff
      shell: bash
      id: get-diff
      run: |
        composer global require davidrjonas/composer-lock-diff:^1.0
        diff=$(~/.composer/vendor/bin/composer-lock-diff --md -p ${{ inputs.working-dir }})
        diff="${diff//'%'/'%25'}"
        diff="${diff//$'\n'/'%0A'}"
        diff="${diff//$'\r'/'%0D'}"
        echo "::set-output name=diff::$diff"
      env:
        COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ inputs.composer-token }}"}}'
